### ISSUE TITLE
Missed some files?

### ISSUE THREAD

**Issue by pelfor** [itxchy/react-ssr-boilerplate#1]
Not working from the scratch

**Comment by mtrifilo** [comment]
@pelfor This project is still a work in progress, so I wouldn't recommend using it until I finish the core features, mainly local and OAuth authentication. I haven't tested this in any vm environments yet either, but that's happening soon.

This should be ready for Free Code Camp students to use by next week, along with initial documentation. This will be changing very rapidly until the first release. I'll keep this issue open until then.

**Comment by mtrifilo** [comment]
1.0.0 is ready.
