### ISSUE TITLE
[v2] eslint false positives for class properties in eslint-loader only

### ISSUE THREAD

**Issue by mtrifilo** [itxchy/react-ssr-boilerplate#2]
`eslint-loader` started emitting `no-undef` errors for class properties during webpack builds after upgrading the eslint dependencies. Oddly, the eslint CLI and VScode eslint plugin do not show these errors.

The problem seems to be in `babel-eslint` as discussed in this issue: https://github.com/eslint/eslint/issues/8720

It sounds like the eslint folks are actively working on a number of bugs, so this will hopefully be fixed soon.

This doesn't affect version 1 of the boilerplate.

**Comment by mtrifilo** [comment]
Fixed with subsequent babel updates.

**Comment by jonnyasmar** [comment]
Yep, make sure your `babel-loader` & `babel-eslint` are the same major version.

**Comment by fallenleavesguy** [comment]
@jonnyasmar work well.Thanks
